apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-spring-kb-deployment
spec:
  selector:
    matchLabels:
      app: docker-spring-kb
  template:
    metadata:
      labels:
        app: docker-spring-kb
    spec:
      containers:
        - name: docker-spring-kb
          image: sutewari/docker-spring-boot
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: docker-spring-kb-service
spec:
  type: NodePort
  selector:
    app: docker-spring-kb
  ports:
    - port: 8085
      targetPort: 8085